FORMAT: 1A
HOST: http://localhost:7080/api/

#UniFi Protect API


## Group AudioLevels

Retrieve AudioLevels.
 
### Get audiolevels of camera [GET /audiolevels/{id}{?start,end}]

+ Parameters
    + id: 564b882cca5fcb5c0670f5b9 (required, string) - ID of the Camera.
    + start: `1464299823082` (required, number) - start time
    + end: `1464299940863` (required, number) - end time

+ Response 200 (application/json)
 
